"""empty message

Revision ID: f71261664371
Revises: 
Create Date: 2020-05-03 18:23:35.443287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71261664371'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proprietarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('dtNasc', sa.Date(), nullable=False),
    sa.Column('qrcode', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('proprietarios')
    # ### end Alembic commands ###
